databases:
  - name: ZAHRA-DB
    plan: free

services:
  - type: web
    name: ZAHRA
    env: python
    plan: free
    buildCommand: |-
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: app.py
      - fromDatabase:
          name: ZAHRA-DB
          property: connectionString
